# Generated by Django 3.1.5 on 2022-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0003_auto_20220420_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
